version: "3"
services:
  postgresql:
    image: "postgres"
    container_name: "test_postgres"
    environment:
      - POSTGRES_USER=vishal
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=db2
    ports:
      - "5433:5433"
  app:
    build: .
    image: app
    container_name: "c_app"
    depends_on:
      - postgresql